---
title: "Occurrence maps"
author: "Francisco Rodriguez-Sanchez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
root <- rprojroot::find_rstudio_root_file()
```



```{r}
library(rSDM)
library(leaflet)
```


```{r}
occs <- as.data.frame(readr::read_csv(file.path(root, "data/locs_30m.csv")))
```


## All species
```{r}
occmap(occs, bg = 'leaflet', pcol = "black") %>%
  addProviderTiles(providers$OpenStreetMap)
```


## C. macloviana
```{r}
occmap(occs[occs$species == "macloviana", ], bg = "leaflet", pcol = "black") %>%
  addProviderTiles(providers$OpenStreetMap)
```


## C. magellanica
```{r}
occmap(occs[occs$species == "magellanica", ], bg = "leaflet", pcol = "black") %>%
  addProviderTiles(providers$OpenStreetMap)
```


## C. microglochin
```{r}
occmap(occs[occs$species == "microglochin", ], bg = "leaflet", pcol = "black") %>%
  addProviderTiles(providers$OpenStreetMap)
```


## C. canescens
```{r}
occmap(occs[occs$species == "canescens", ], bg = "leaflet", pcol = "black") %>%
  addProviderTiles(providers$OpenStreetMap)
```


## C. maritima
```{r}
occmap(occs[occs$species == "maritima", ], bg = "leaflet", pcol = "black") %>%
  addProviderTiles(providers$OpenStreetMap)
```


