# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

warnings_are_errors: false

dist: trusty

apt_packages:
  - gdal-bin
  - libproj-dev
  - libgdal-dev
  - libudunits2-dev
