# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

dist: trusty

before_install:
  - sudo apt-get install --yes libproj-dev libgdal-dev
