---
title: "Models"
author: "Francisco Rodriguez-Sanchez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, cache = TRUE)
opts_knit$set(root.dir = "../")
```


```{r}
library(readr)
library(dplyr)
library(dismo)

```

```{r}
locs <- as.data.frame(read_csv("./data/locs_30m.csv"))
bioclim <- as.data.frame(read_csv("./data/bioclim_pres_30m.csv"))
```

Select only 10000 background points:

```{r}
background <- bioclim %>%
  dplyr::select(starts_with("bio")) %>%
  sample_n(size = 10000)

bioclim <- locs %>%
  dplyr::select(starts_with("bio")) %>%
  bind_rows(background)

pres.bg.id <- c(rep(1, times = nrow(locs)), rep(0, 10000))
  
```



```{r mod_crosval, eval = crosval}
mod.crosval <- maxent(bioclim, pres.bg.id, 
              args = c("responsecurves", "writeplotdata", "threads=4", "nothreshold",
                       "replicates=10", "replicatetype=crossvalidate"),
              path = paste0(getwd(), "/analyses/maxent/", species, "/crosval"))
```


```{r mod}
mod <- maxent(bioclim, pres.bg.id, 
              args = c("responsecurves", "writeplotdata", "threads=4", "nothreshold"),
                     #  "replicates=20", "replicatetype=crossvalidate"),
              path = paste0(getwd(), "/analyses/maxent/", species))
#mod
```


# Load present bioclim rasters

```{r load_presclim}
bioclim.pres <- read_presclim()
```



# Plot present suitability
```{r project_pres}
pres.pred <- predict(mod, bioclim.pres)
plot(pres.pred)
writeRaster(pres.pred, filename = paste0("./analyses/maxent/", species, "/", species, "_proj_pres.grd"),
            overwrite = TRUE)
```


# Project2future

## RCP 4.5
```{r project_rcp45}
pred.rcp45 <- combine_pred(mod, "rcp45")
plot(pred.rcp45)
writeRaster(pred.rcp45, filename = paste0("./analyses/maxent/", species, "/", species, "_proj_rcp45.grd"),
            overwrite = TRUE)
```


## RCP 8.5
```{r project_rcp85}
pred.rcp85 <- combine_pred(mod, "rcp85")
plot(pred.rcp85)
writeRaster(pred.rcp85, filename = paste0("./analyses/maxent/", species, "/", species, "_proj_rcp85.grd"),
            overwrite = TRUE)
```


```{r}
devtools::session_info()
```

