---
title: 'Figs. Future Suitability'
author: "Francisco Rodriguez-Sanchez"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
root <- rprojroot::find_rstudio_root_file()

library(knitr)
knitr::opts_chunk$set(echo = TRUE, out.height = '7in', out.width = '9in',
                      fig.path = paste0(root, "/manuscript/figures/"))
```


 
## RCP4.5

### Mean suitability among the 5 climate models
```{r rcp45_mean}
rcp45.mean <- plot_ensemble("mean", "rcp45")
```

### SD suitability among the 5 climate models
```{r rcp45_sd}
rcp45.sd <- plot_ensemble("sd", "rcp45")
```

### Difference Future - Present suitability
```{r rcp45_diff}
rcp45.diff <- compare_suitab_futu_pres(rcp45.mean)
```



## RCP8.5

### Mean suitability among the 5 climate models
```{r rcp85_mean}
rcp85.mean <- plot_ensemble("mean", "rcp85")
```

### SD suitability among the 5 climate models
```{r rcp85_sd}
rcp85.sd <- plot_ensemble("sd", "rcp85")
```

### Difference Future - Present suitability
```{r rcp85_diff}
rcp85.diff <- compare_suitab_futu_pres(rcp85.mean)
```



```{r}
devtools::session_info()
```



